package com.mcpintelligence.fr3k.core

import android.content.Context
import android.content.pm.PackageManager
import android.os.Build
import android.os.Environment
import android.os.StatFs
import java.io.File
import java.security.MessageDigest

/**
 * Diagnostic bundle exporter (§49). Collects non-sensitive operational data
 * and serialises it as JSON + human-readable text. Secrets are NEVER included —
 * only their presence ("token_set": true|false).
 */
object DiagnosticsExporter {

    data class Bundle(
        val app: Map<String, String>,
        val device: Map<String, String>,
        val permissions: Map<String, Boolean>,
        val foregroundServices: List<String>,
        val capabilities: List<String>,
        val plugins: List<String>,
        val automations: List<String>,
        val automationLogs: List<String>,
        val capabilitiesInventory: Map<String, String>,
        val notes: List<String>,
    )

    fun collect(
        context: Context,
        fr3kCore: Fr3kCore,
        foregroundServices: List<String>,
    ): Bundle {
        val identity = fr3kCore.identity
        val pkgInfo = try {
            context.packageManager.getPackageInfo(context.packageName, 0)
        } catch (_: PackageManager.NameNotFoundException) { null }
        val sdk = Build.VERSION.SDK_INT
        val release = Build.VERSION.RELEASE ?: "?"
        val model = "${Build.MANUFACTURER} ${Build.MODEL}"
        val storage = readableStorage(context)
        return Bundle(
            app = mapOf(
                "name" to context.getString(context.applicationInfo.labelRes),
                "package" to context.packageName,
                "versionName" to (pkgInfo?.versionName ?: "?"),
                "versionCode" to (pkgInfo?.longVersionCode?.toString() ?: "?"),
                "firstInstall" to (pkgInfo?.firstInstallTime?.toString() ?: "?"),
                "lastUpdate" to (pkgInfo?.lastUpdateTime?.toString() ?: "?"),
            ),
            device = mapOf(
                "deviceId" to identity.deviceId,
                "fingerprint" to identity.fingerprint(),
                "androidId" to identity.androidId,
                "platform" to identity.platform,
                "sdk" to sdk.toString(),
                "release" to release,
                "model" to model,
                "manufacturer" to Build.MANUFACTURER,
                "storage" to storage,
                "nowMs" to System.currentTimeMillis().toString(),
            ),
            permissions = permissionStatuses(context),
            foregroundServices = foregroundServices,
            capabilities = fr3kCore.capabilityRegistry.snapshot.value.keys.toList().sorted(),
            plugins = fr3kCore.pluginManager.statuses.map { (id, status) -> "$id=$status" },
            automations = fr3kCore.automationEngine.all().map { "${it.id} [${it.trigger.type}] → ${actionName(it.action)} (fired ${it.fireCount})" },
            automationLogs = fr3kCore.automationEngine.logs().take(40).map { entry ->
                "${entry.timestamp}: ${entry.title} → ${entry.outcome}"
            },
            capabilitiesInventory = fr3kCore.capabilityRegistry.snapshot.value.entries.associate { (id, cap) ->
                id to "${cap.tier}/${if (cap.experimental) "experimental" else "stable"}"
            },
            notes = listOf(
                "Diagnostic bundle is non-sensitive; secrets are scrubbed.",
                "Generated by FR3K HUD diagnostics exporter.",
            ),
        )
    }

    fun toJson(bundle: Bundle): String = buildString {
        append("{\n")
        appendKv("app", bundle.app, indent = "  ")
        append(",\n")
        appendKv("device", bundle.device, indent = "  ")
        append(",\n")
        appendKv("permissions", bundle.permissions, indent = "  ")
        append(",\n")
        appendList("foregroundServices", bundle.foregroundServices, indent = "  ")
        append(",\n")
        appendList("capabilities", bundle.capabilities, indent = "  ")
        append(",\n")
        appendList("plugins", bundle.plugins, indent = "  ")
        append(",\n")
        appendList("automations", bundle.automations, indent = "  ")
        append(",\n")
        appendList("automationLogs", bundle.automationLogs, indent = "  ")
        append(",\n")
        appendKv("capabilitiesInventory", bundle.capabilitiesInventory, indent = "  ")
        append(",\n")
        appendList("notes", bundle.notes, indent = "  ")
        append("\n}\n")
    }

    fun toText(bundle: Bundle): String = buildString {
        append("FR3K HUD — diagnostic bundle\n")
        append("Generated: ${java.util.Date()}\n")
        append("\n")
        appendSection("Application", bundle.app)
        appendSection("Device", bundle.device)
        appendSection("Permissions", bundle.permissions.mapValues { (_, v) -> if (v) "granted" else "denied" })
        append("Foreground services: ${bundle.foregroundServices.joinToString(", ")}\n")
        append("Capabilities: ${bundle.capabilities.joinToString(", ")}\n")
        append("Plugins: ${bundle.plugins.joinToString(", ")}\n")
        append("Automations: ${bundle.automations.joinToString(", ")}\n")
        append("Recent automation logs:\n")
        bundle.automationLogs.forEach { append("  $it\n") }
        append("\n")
        append("Notes: ${bundle.notes.joinToString("; ")}\n")
    }

    private fun StringBuilder.appendSection(title: String, map: Map<String, String>) {
        append(title).append('\n')
        map.forEach { (k, v) -> append("  ").append(k).append(" = ").append(v).append('\n') }
        append('\n')
    }

    private fun StringBuilder.appendKv(name: String, map: Map<String, *>, indent: String) {
        append(indent).append('"').append(name).append("\": {")
        val entries = map.entries.toList()
        entries.forEachIndexed { i, (k, v) ->
            append("\n").append(indent).append(indent).append('"').append(k).append("\": \"").append(escape(v.toString())).append('"')
            if (i < entries.size - 1) append(",")
        }
        if (entries.isNotEmpty()) append("\n").append(indent)
        append("}")
    }

    private fun StringBuilder.appendList(name: String, list: List<String>, indent: String) {
        append(indent).append('"').append(name).append("\": [")
        list.forEachIndexed { i, s ->
            append("\n").append(indent).append(indent).append('"').append(escape(s)).append('"')
            if (i < list.size - 1) append(",")
        }
        if (list.isNotEmpty()) append("\n").append(indent)
        append("]")
    }

    private fun escape(s: String) = s.replace("\\", "\\\\").replace("\"", "\\\"")

    private fun actionName(action: AutomationEngine.Action): String = when (action) {
        is AutomationEngine.Action.RunCommand -> "cmd:${action.commandId}"
        is AutomationEngine.Action.OpenPalette -> "open_palette"
        is AutomationEngine.Action.OpenAskAboutThis -> "open_ask"
        is AutomationEngine.Action.SendToMesh -> "mesh"
        is AutomationEngine.Action.SendToDevice -> "device:${action.deviceId}"
        is AutomationEngine.Action.Notify -> "notify"
    }

    private fun permissionStatuses(context: Context): Map<String, Boolean> {
        val permissions = listOf(
            "android.permission.SYSTEM_ALERT_WINDOW",
            "android.permission.POST_NOTIFICATIONS",
            "android.permission.RECORD_AUDIO",
            "android.permission.CAMERA",
            "android.permission.ACCESS_FINE_LOCATION",
            "android.permission.ACCESS_COARSE_LOCATION",
            "android.permission.PACKAGE_USAGE_STATS",
            "android.permission.QUERY_ALL_PACKAGES",
        )
        return permissions.associateWith { perm ->
            try {
                context.checkSelfPermission(perm) == PackageManager.PERMISSION_GRANTED
            } catch (_: Throwable) { false }
        }
    }

    private fun readableStorage(context: Context): String {
        return try {
            val path = context.filesDir.absolutePath
            val stat = StatFs(path)
            val totalBytes = stat.totalBytes
            val availBytes = stat.availableBytes
            "${human(availBytes)} free / ${human(totalBytes)} total"
        } catch (_: Throwable) { "unknown" }
    }

    private fun human(bytes: Long): String {
        val units = listOf("B", "KB", "MB", "GB", "TB")
        var v = bytes.toDouble()
        var i = 0
        while (v >= 1024 && i < units.lastIndex) { v /= 1024; i++ }
        return "%.1f %s".format(v, units[i])
    }
}